# Generated by Django 2.2.4 on 2021-04-02 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='breakfast',
            new_name='food_item',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='dinner',
            new_name='meal_type',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='cardio',
            new_name='workout_type',
        ),
        migrations.RemoveField(
            model_name='food',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='food',
            name='snacks',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='other',
        ),
    ]
